[project]
name = "repomap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.7.0",
    "google-genai>=1.24.0",
    "google-generativeai>=0.8.5",
    "watchdog>=3.0.0",
]
